services:
  discord-dota-web:
    image: orgmcr.or-gm.com/osmargm1202/discord-dota-web:latest
    container_name: discord-dota-web
    restart: always
    ports:
      - "8092:8092"
    network_mode: bridge
    environment:
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - PORT=8092
